PROJECT_NAME ?= tt_um_algofoogle_analog_junk
PROJECT_LVS_VERILOG ?= ../src/project.v # ../src/LVS-project.v
# MAGICEXEC ?= magic -rcfile magicrc -noconsole -dnull
MAGICEXEC ?= magic -rcfile $(PDK_MAGICRC) -noconsole -dnull

.PHONY: lvs magic start

antenna:
	$(MAGICEXEC) tcl/antenna.tcl $(PROJECT_NAME)
	rm -f *.ext

drc:
	$(MAGICEXEC) tcl/drc.tcl $(PROJECT_NAME)
	
%.lvs.spice: %.mag
	$(MAGICEXEC) tcl/extract_for_lvs.tcl $*
	rm -f *.ext

%.sim.spice: %.mag
	$(MAGICEXEC) tcl/extract_for_sim.tcl $*
	rm -f *.ext

lvs.report: $(PROJECT_NAME).lvs.spice $(PROJECT_LVS_VERILOG)
	netgen -batch eval 'set project $(PROJECT_NAME) ; set report_file "lvs.report" ; source tcl/lvs_netgen.tcl'

%.lvs.report: %.lvs.spice
	cp $*.lvs.spice $*.lvs.spice.backup
	netgen -batch eval 'set project $* ; set report_file "$@" ; source tcl/lvs_netgen.tcl'


lvs: lvs.report
	@bash -c 'propOk=OK; match=FAIL; port=OK; \
	if grep -q "match uniquely"                             lvs.report; then match=OK; fi; \
	if grep -q "Property errors were found"                 lvs.report; then propOk=FAIL; fi; \
	if grep -q "failed pin matching"                        lvs.report; then match=FAIL; fi; \
	if grep -q "Final result: Netlists do not match"        lvs.report; then match=FAIL; fi; \
	if grep -q "port errors"                                lvs.report; then port=FAIL; fi; \
	if grep -q "Final result: Circuits match uniquely\."    lvs.report; then match=OK; fi; \
	if [ "$$match" == "OK" ] && [ "$$propOk" == "OK" ] && [ "$$port" == "OK" ]; then \
		echo "LVS OK"; \
		exit 0; \
	else \
		echo "LVS FAIL: match=$$match properties=$$propOk port=$$port"; \
		exit 1; \
	fi'

update_gds:
	mkdir -p ../gds ../lef
	$(MAGICEXEC) tcl/update_gds_lef.tcl $(PROJECT_NAME)

clean:
	rm -f *lvs.report *.lvs.spice *.nodes
